-- SQLite
/*CREATE TABLE IF NOT EXISTS Locations (
	userId INTEGER PRIMARY KEY AUTOINCREMENT,
	plots_name Text DEFAULT "Map1.kml"
) */
DROP TABLE IF EXISTS Comments;
DROP TABLE IF EXISTS Posts;
DROP TABLE IF EXISTS Writers;